### ISSUE TITLE
random gifs

### ISSUE THREAD

**Issue by techgaun** [techgaun/ex_mustang#33]
maybe be better about getting random gifs.. well mustang yet does not have any gif stuff so that should be built first.. this might be little harder unless we can use an API from giphy or something similar so we can filter by things like nsfw..

if we use giphy api, one fun thing would be to _hear_ common exclamation words and then respond with GIPHY TRANSLATE

**Comment by theodowling** [comment]
Hi @techgaun - are you happy with me taking this on for hacktoberfest? Should be pretty easy to respond with random gif using giphy api.

**Comment by techgaun** [comment]
hey @theodowling thanks I've added appropriate labels. Good luck with hacktoberfest

**Comment by techgaun** [comment]
closed by #87
